pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: self
    submodules: true
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
    displayName: Install ninja
  - script: cargo build -vv --all
    displayName: Cargo build
  - script: cargo test -vv --all
    displayName: Cargo test
